name: "nix build and push to cache"
on:
  workflow_dispatch:
  push:
    branches:
      - devel

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: nixbuild/nix-quick-install-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-24.11
    - uses: nix-community/cache-nix-action@v6
      with:
        primary-key: nix-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
        restore-prefixes-first-match: nix-${{ runner.os }}-${{ runner.arch }}
    - uses: cachix/cachix-action@v14
      with:
        name: elmerfem
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: nix build
      run: |
        nix build -L
        nix build .#gui -L
        nix build .#full -L
